"""Pre-built experiment templates.

These mirror the real experiments a food-delivery / marketplace PM would run,
giving one-click starting points on the Create Experiment screen. Each carries
a realistic primary metric, sensible secondaries and a plausible true effect
for the simulator.
"""
from __future__ import annotations

EXPERIMENT_TEMPLATES: list[dict] = [
    {
        "id": "checkout",
        "name": "Old Checkout vs New Checkout",
        "area": "Checkout",
        "icon": "shopping-cart",
        "primary_metric_key": "checkout_conversion",
        "secondary_metric_keys": ["conversion_rate", "cart_abandonment", "aov", "arpu"],
        "control_name": "Current Checkout",
        "treatment_name": "Redesigned Checkout",
        "hypothesis": "A single-page checkout with saved payment methods will reduce friction and lift checkout conversion.",
        "business_objective": "Increase completed orders without harming average order value.",
        "success_criteria": "≥3% relative lift in checkout conversion at 95% confidence with no revenue regression.",
        "suggested_effect_pct": 6.0,
    },
    {
        "id": "coupon-ui",
        "name": "New Coupon UI",
        "area": "Growth",
        "icon": "ticket",
        "primary_metric_key": "coupon_usage",
        "secondary_metric_keys": ["conversion_rate", "aov", "arpu", "orders"],
        "control_name": "Legacy Coupon Banner",
        "treatment_name": "Smart Coupon Carousel",
        "hypothesis": "Surfacing personalised coupons more prominently will increase redemption and order rate.",
        "business_objective": "Drive incremental orders from promotion-sensitive users.",
        "success_criteria": "Higher coupon usage and conversion with ARPU held flat or positive.",
        "suggested_effect_pct": 9.0,
    },
    {
        "id": "ranking",
        "name": "Restaurant Ranking Algorithm",
        "area": "Discovery",
        "icon": "list-ordered",
        "primary_metric_key": "conversion_rate",
        "secondary_metric_keys": ["ctr", "restaurant_views", "aov", "customer_satisfaction"],
        "control_name": "Popularity Ranking",
        "treatment_name": "Personalised ML Ranking",
        "hypothesis": "Ranking restaurants by predicted relevance will help users convert faster.",
        "business_objective": "Improve discovery efficiency and conversion.",
        "success_criteria": "Higher conversion and CTR without lowering satisfaction.",
        "suggested_effect_pct": 4.5,
    },
    {
        "id": "recommendations",
        "name": "Recommendation Algorithm",
        "area": "Discovery",
        "icon": "sparkles",
        "primary_metric_key": "orders",
        "secondary_metric_keys": ["conversion_rate", "aov", "repeat_purchase_rate", "arpu"],
        "control_name": "Rule-based Recommendations",
        "treatment_name": "Collaborative-Filtering Recommendations",
        "hypothesis": "Better 'you might also like' recommendations will increase orders per user.",
        "business_objective": "Grow order frequency and basket size.",
        "success_criteria": "More orders per user and higher ARPU.",
        "suggested_effect_pct": 5.5,
    },
    {
        "id": "homepage",
        "name": "Homepage Redesign",
        "area": "Homepage",
        "icon": "layout-dashboard",
        "primary_metric_key": "ctr",
        "secondary_metric_keys": ["bounce_rate", "conversion_rate", "session_length"],
        "control_name": "Current Homepage",
        "treatment_name": "Redesigned Homepage",
        "hypothesis": "A cleaner, card-first homepage will increase engagement and reduce bounce.",
        "business_objective": "Improve top-of-funnel engagement.",
        "success_criteria": "Higher CTR and lower bounce with stable conversion.",
        "suggested_effect_pct": 7.0,
    },
    {
        "id": "search",
        "name": "Search Algorithm",
        "area": "Search",
        "icon": "search",
        "primary_metric_key": "conversion_rate",
        "secondary_metric_keys": ["searches", "ctr", "bounce_rate", "aov"],
        "control_name": "Keyword Search",
        "treatment_name": "Semantic Search",
        "hypothesis": "Semantic search will return more relevant results and convert more searchers.",
        "business_objective": "Turn search intent into orders.",
        "success_criteria": "Higher conversion among searching users.",
        "suggested_effect_pct": 3.5,
    },
    {
        "id": "delivery-fee",
        "name": "Delivery Fee Pricing",
        "area": "Pricing",
        "icon": "indian-rupee",
        "primary_metric_key": "conversion_rate",
        "secondary_metric_keys": ["aov", "arpu", "cart_abandonment", "orders"],
        "control_name": "Flat Delivery Fee",
        "treatment_name": "Dynamic Delivery Fee",
        "hypothesis": "Dynamic delivery pricing can protect margin while keeping conversion healthy.",
        "business_objective": "Optimise the fee/conversion trade-off.",
        "success_criteria": "ARPU up with conversion not significantly down.",
        "suggested_effect_pct": 2.5,
    },
    {
        "id": "payment-flow",
        "name": "Payment Flow",
        "area": "Payments",
        "icon": "credit-card",
        "primary_metric_key": "checkout_conversion",
        "secondary_metric_keys": ["cart_abandonment", "conversion_rate", "arpu"],
        "control_name": "Multi-step Payment",
        "treatment_name": "One-tap Payment",
        "hypothesis": "One-tap payment with tokenised cards will cut drop-off at payment.",
        "business_objective": "Reduce payment-stage abandonment.",
        "success_criteria": "Higher checkout conversion, lower abandonment.",
        "suggested_effect_pct": 8.0,
    },
    {
        "id": "menu-design",
        "name": "Menu Design",
        "area": "Menu",
        "icon": "book-open",
        "primary_metric_key": "menu_opens",
        "secondary_metric_keys": ["conversion_rate", "aov", "session_length"],
        "control_name": "List Menu",
        "treatment_name": "Visual Menu with Photos",
        "hypothesis": "Photo-rich menus will increase engagement and basket size.",
        "business_objective": "Improve menu engagement and AOV.",
        "success_criteria": "More menu opens and higher AOV.",
        "suggested_effect_pct": 6.5,
    },
    {
        "id": "restaurant-cards",
        "name": "Restaurant Cards",
        "area": "Discovery",
        "icon": "credit-card",
        "primary_metric_key": "ctr",
        "secondary_metric_keys": ["restaurant_views", "conversion_rate", "bounce_rate"],
        "control_name": "Compact Cards",
        "treatment_name": "Rich Media Cards",
        "hypothesis": "Richer restaurant cards with ratings and ETA will increase click-through.",
        "business_objective": "Improve browse-to-click efficiency.",
        "success_criteria": "Higher CTR without raising bounce.",
        "suggested_effect_pct": 5.0,
    },
]
