// xlsx / jspdf are heavy and only needed on demand — lazy-loaded inside the
// export functions to keep them out of the initial bundle.
import { api } from "@/services/api";
import { formatMetric } from "@/lib/format";
import { DECISION_META } from "@/lib/decisions";
import type { AnalysisResponse, ExperimentDetail, MetricSpec } from "@/types";

function saveBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function unitOf(metrics: MetricSpec[], key: string) {
  return metrics.find((m) => m.key === key)?.unit ?? "";
}

function labelOf(metrics: MetricSpec[], key: string) {
  return metrics.find((m) => m.key === key)?.label ?? key;
}

/** Server-generated CSV (authenticated). */
export async function downloadCsv(exp: ExperimentDetail) {
  const res = await api.get(`/experiments/${exp.id}/export.csv`, { responseType: "blob" });
  saveBlob(res.data, `${exp.key}-results.csv`);
}

/** Client-generated Excel workbook with formatted results + segments. */
export async function downloadExcel(exp: ExperimentDetail, analysis: AnalysisResponse, metrics: MetricSpec[]) {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();

  const resultRows = analysis.statistical_results.map((r) => ({
    Metric: labelOf(metrics, r.metric_key),
    Primary: r.is_primary ? "Yes" : "",
    Test: r.test_name,
    Control: formatMetric(unitOf(metrics, r.metric_key), r.control_value),
    Treatment: formatMetric(unitOf(metrics, r.metric_key), r.treatment_value),
    "Lift %": r.relative_lift_pct.toFixed(2),
    "p-value": r.p_value.toFixed(5),
    Significant: r.significant ? "Yes" : "No",
    "CI low": r.ci_low.toFixed(5),
    "CI high": r.ci_high.toFixed(5),
    "Effect size": r.effect_size.toFixed(4),
    "Effect": r.effect_label,
    "Power %": (r.achieved_power * 100).toFixed(1),
  }));
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(resultRows), "Results");

  const segRows = analysis.segments.map((s) => ({
    Dimension: s.dimension,
    Segment: s.segment,
    Control: formatMetric(unitOf(metrics, s.metric_key), s.control_mean),
    Treatment: formatMetric(unitOf(metrics, s.metric_key), s.treatment_mean),
    "Lift %": s.lift_pct.toFixed(2),
    "p-value": s.p_value.toFixed(5),
    Significant: s.significant ? "Yes" : "No",
    "n (C/T)": `${s.control_n}/${s.treatment_n}`,
  }));
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(segRows), "Segments");

  const r = analysis.report;
  const summaryRows = [
    { Field: "Experiment", Value: exp.name },
    { Field: "Decision", Value: DECISION_META[r.decision].label },
    { Field: "Confidence", Value: `${r.confidence_score}/100` },
    { Field: "Headline", Value: r.headline },
    { Field: "Projected Annual Revenue", Value: r.sections.projected_annual_revenue ?? 0 },
    { Field: "Generated by", Value: r.generated_by },
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(summaryRows), "Summary");

  const buf = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  saveBlob(new Blob([buf], { type: "application/octet-stream" }), `${exp.key}-report.xlsx`);
}

/** Client-generated executive PDF report. */
export async function downloadPdf(exp: ExperimentDetail, analysis: AnalysisResponse, metrics: MetricSpec[]) {
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const r = analysis.report;
  const meta = DECISION_META[r.decision];
  let y = 54;

  // Header band
  doc.setFillColor(12, 14, 20);
  doc.rect(0, 0, W, 90, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Executive Experiment Report", 40, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(160, 170, 190);
  doc.text(exp.name, 40, 66);

  y = 118;
  // Decision line
  doc.setTextColor(30, 30, 40);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(`Recommendation: ${meta.label.toUpperCase()}`, 40, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90, 95, 110);
  doc.text(`Decision confidence: ${r.confidence_score}/100  ·  Generated by: ${r.generated_by}`, 40, y + 16);
  y += 40;

  // Summary paragraph (strip markdown asterisks)
  doc.setTextColor(40, 44, 56);
  doc.setFontSize(10);
  const summary = r.summary.replace(/\*\*/g, "").replace(/\*/g, "");
  const lines = doc.splitTextToSize(summary, W - 80);
  doc.text(lines, 40, y);
  y += lines.length * 13 + 12;

  // Metric table (primary first)
  const rows = [...analysis.statistical_results]
    .sort((a, b) => Number(b.is_primary) - Number(a.is_primary))
    .map((s) => [
      labelOf(metrics, s.metric_key) + (s.is_primary ? "  ★" : ""),
      formatMetric(unitOf(metrics, s.metric_key), s.control_value),
      formatMetric(unitOf(metrics, s.metric_key), s.treatment_value),
      `${s.relative_lift_pct >= 0 ? "+" : ""}${s.relative_lift_pct.toFixed(2)}%`,
      s.p_value < 0.0001 ? "<0.0001" : s.p_value.toFixed(4),
      s.significant ? "Yes" : "No",
    ]);

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Control", "Treatment", "Lift", "p-value", "Sig."]],
    body: rows,
    theme: "grid",
    headStyles: { fillColor: [124, 108, 255], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 8.5, textColor: [40, 44, 56] },
    alternateRowStyles: { fillColor: [246, 247, 250] },
    margin: { left: 40, right: 40 },
  });

  y = (doc as any).lastAutoTable.finalY + 24;

  // Narrative sections
  const sections: [string, string | undefined][] = [
    ["Why it happened", r.sections.why_it_won],
    ["Business impact", r.sections.business_impact],
    ["Risk assessment", r.sections.risk],
    ["Recommendation", r.sections.recommendation],
  ];
  for (const [title, body] of sections) {
    if (!body) continue;
    if (y > doc.internal.pageSize.getHeight() - 90) {
      doc.addPage();
      y = 54;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(20, 22, 30);
    doc.text(title, 40, y);
    y += 15;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(60, 64, 78);
    const wrapped = doc.splitTextToSize(body.replace(/\*\*/g, "").replace(/\*/g, ""), W - 80);
    doc.text(wrapped, 40, y);
    y += wrapped.length * 12 + 16;
  }

  doc.save(`${exp.key}-executive-report.pdf`);
}
